"""PlatformIO pre-build hook: link the Macintosh's ROM and boot disc in.

Neither is in the repository. Both are read from roms/mac/, which is
gitignored like the rest of roms/:

  roms/mac/macplus.rom   the Mac Plus v3 ROM, 128kB, checksum 4D1F8172
  roms/mac/boot.img      a raw 400k/800k/1.4MB disc image to boot from

When both are there this writes src/mac/mac_media.S, which pulls them in
with .incbin (so they land in flash as they are, no C array in between),
and defines HAVE_MAC_MEDIA. That .S is generated with absolute paths into
this checkout and is gitignored too. Without the files the firmware still
builds and says what is missing when it boots.

The ROM is checked here rather than on the device: umac only knows how to
patch the v3 ROM, and anything else would boot to a sad Mac or not at all.
MAME splits the ROM into two halves, 342-0341-c (high bytes) and
342-0342-b (low bytes); tools/make_macplus_rom.py joins them.
"""
import os
import struct

Import("env")  # noqa: F821  (injected by PlatformIO)

project = env.subst("$PROJECT_DIR")
media_dir = os.path.join(project, "roms", "mac")
rom = os.path.join(media_dir, "macplus.rom")
disc = os.path.join(media_dir, "boot.img")
out = os.path.join(env.subst("$PROJECT_SRC_DIR"), "mac", "mac_media.S")


def rom_ok(path):
    data = open(path, "rb").read()
    if len(data) != 0x20000:
        return "is %d bytes, the Mac Plus ROM is 131072" % len(data)
    stored = struct.unpack(">I", data[:4])[0]
    words = struct.unpack(">%dH" % ((len(data) - 4) // 2), data[4:])
    if stored != 0x4D1F8172 or (sum(words) & 0xFFFFFFFF) != stored:
        return "is not the Mac Plus v3 ROM (checksum %08X, want 4D1F8172)" % stored
    return None


problem = None
if not os.path.isfile(rom):
    problem = "no roms/mac/macplus.rom"
elif not os.path.isfile(disc):
    problem = "no roms/mac/boot.img"
else:
    problem = rom_ok(rom)
    if problem:
        problem = "roms/mac/macplus.rom " + problem

if problem:
    if os.path.isfile(out):
        os.remove(out)
    print("Mac: %s, building without it" % problem)
else:
    # Sizes and times go into the text so that replacing either file changes
    # this one, which is the only thing the build tracks.
    stamp = " ".join("%d/%d" % (os.path.getsize(p), int(os.path.getmtime(p)))
                     for p in (rom, disc))
    text = """/* GENERATED by tools/local_mac.py - do not edit, do not commit.
 * Somebody else's ROM and disc, linked into flash as they are.
 * %s */
    .section .rodata.mac_media, "a"
    .balign 16
    .global mac_rom_image
mac_rom_image:
    .incbin "%s"
    .global mac_rom_image_end
mac_rom_image_end:
    .balign 16
    .global mac_disc_image
mac_disc_image:
    .incbin "%s"
    .global mac_disc_image_end
mac_disc_image_end:
""" % (stamp, rom, disc)
    if not os.path.isfile(out) or open(out).read() != text:
        open(out, "w").write(text)
    env.Append(CPPDEFINES=["HAVE_MAC_MEDIA"])
    print("Mac: ROM and %s (%d kB) linked in" % (os.path.relpath(disc, project),
                                                 os.path.getsize(disc) // 1024))
