#!/usr/bin/env python3
"""The PC's text font, from your own MS-DOS: EGA.CPI's code pages 437 and
860 (Portuguese) at 8x16.

    python3 tools/make_pc_font.py [roms/pc/EGA.CPI] [src/pc/pc_font_data.c]

lib/pc8086's own font has only 0x00-0x7F and a dozen line pieces above
that: no accented letters, no double frames, no shading. EGA.CPI (in
C:\\DOS of MS-DOS 5 and 6) carries the VGA's full set. Like every ROM here,
neither the .CPI nor the generated C is in the repository; tools/
local_bios.py defines HAVE_PC_FONT when the C is there, and without it the
PC falls back to the lib's font.

The .CPI is the "FONT" format: a file header pointing at a font info
header, then one code page entry header per code page, each pointing at a
code page info header followed by its fonts (height, width, two aspect
bytes, a character count, then the bitmaps).
"""
import struct
import sys


def fonts(data):
    if data[0] != 0xFF or data[1:8] != b"FONT   ":
        raise SystemExit("not a FONT-format .CPI")
    fih = struct.unpack_from("<I", data, 0x13)[0]
    n = struct.unpack_from("<H", data, fih)[0]
    cpeh = fih + 2
    for _ in range(n):
        size, nxt, dev_type = struct.unpack_from("<HIH", data, cpeh)
        dev = data[cpeh + 8:cpeh + 16].decode("ascii", "replace").strip()
        cp = struct.unpack_from("<H", data, cpeh + 16)[0]
        cpih = struct.unpack_from("<I", data, cpeh + 24)[0]
        _ver, nfonts, _sz = struct.unpack_from("<HHH", data, cpih)
        at = cpih + 6
        for _ in range(nfonts):
            h, w, _ya, _xa, chars = struct.unpack_from("<BBBBH", data, at)
            at += 6
            nbytes = chars * h * ((w + 7) // 8)
            yield cp, dev, h, w, chars, data[at:at + nbytes]
            at += nbytes
        cpeh = nxt


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "roms/pc/EGA.CPI"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/pc/pc_font_data.c"
    data = open(src, "rb").read()
    tables = {}
    for cp in (437, 860):
        found = [f for f in fonts(data) if f[0] == cp and f[2] == 16 and f[3] == 8 and f[4] == 256]
        if not found:
            raise SystemExit("%s has no code page %d font at 8x16" % (src, cp))
        tables[cp] = found[0][5]
    with open(out, "w") as f:
        f.write("/* Generated by tools/make_pc_font.py from %s: code pages 437 and 860,\n"
                " * 8x16. Not in the repository; see that script. */\n" % src.split("/")[-1])
        f.write("#include <stdint.h>\n")
        for cp, bitmap in tables.items():
            f.write("\nconst uint8_t pc_font_cp%d[256 * 16] = {\n" % cp)
            for i in range(0, 4096, 16):
                f.write("    " + ", ".join("0x%02X" % b for b in bitmap[i:i + 16]) + ",\n")
            f.write("};\n")
    print("%s: code pages 437 and 860, 8x16 -> %s" % (src, out))


if __name__ == "__main__":
    main()
