#!/usr/bin/env python3
"""The Commodore 64's ROMs, as C arrays for lib/c64.

    python3 tools/make_c64_roms.py [roms/c64] [src/c64/c64_rom_data.c]

Reads basic.bin (8kB), kernal.bin (8kB), chargen.bin (4kB) and 1541.bin
(16kB, the drive's DOS) from the folder and writes the four arrays the core
declares in lib/c64/src/roms/*.h. Checks each against the SHA-1 of the dump
this was built and tested with, and says so if one differs (it still
writes it: another revision may well work).

The KERNAL gets three bytes changed, as T-HMI-C64's own copy has them:
the SEI that opens IECIN ($EE13), IECOUT ($ED40) and the wait for the
clock line ($EDCC) becomes a BRK, which lib/c64's Hooks.cpp catches and
answers from the emulated 1541. Without them the KERNAL talks to a serial
bus nobody is on: ?DEVICE NOT PRESENT. Found by comparing the two dumps:
these three bytes are the only difference.

Neither the ROMs nor the generated file are in the repository: they are
Commodore's, and only on the owner's machine (from VICE's C64 and DRIVES
folders). tools/local_bios.py turns HAVE_C64_ROMS on when the file exists.
"""
import hashlib
import os
import sys

ROMS = [
    ("basic.bin", "basic_rom", 8192, "79015323128650c742a3694c9429aa91f355905e"),
    ("kernal.bin", "kernal_rom", 8192, "1d503e56df85a62fee696e7618dc5b4e781df1bb"),
    ("chargen.bin", "charset_rom", 4096, "adc7c31e18c7c7413d54802ef2f4193da14711aa"),
    ("1541.bin", "rom_1541", 16384, "ab16f56989b27d89babe5f89c5a8cb3da71a82f0"),
]


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "roms/c64"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/c64/c64_rom_data.c"
    out = ["/* GENERATED by tools/make_c64_roms.py - do not edit.",
           " *",
           " * Commodore's ROMs, from local files. This file is in .gitignore on",
           " * purpose and must not be committed or published.",
           " */"]
    for name, sym, size, sha in ROMS:
        data = open(os.path.join(src, name), "rb").read()
        if len(data) != size:
            sys.exit("%s is %d bytes, expected %d" % (name, len(data), size))
        if hashlib.sha1(data).hexdigest() != sha:
            print("note: %s is not the tested dump (%s)" % (name, hashlib.sha1(data).hexdigest()))
        if sym == "kernal_rom":
            data = bytearray(data)
            for addr in (0xEE13, 0xED40, 0xEDCC):
                if data[addr - 0xE000] != 0x78:
                    sys.exit("kernal: $%04X is $%02X, expected SEI ($78)" % (addr, data[addr - 0xE000]))
                data[addr - 0xE000] = 0x00
        out.append("const unsigned char %s[%d] = {" % (sym, size))
        for i in range(0, size, 16):
            out.append("  " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
        out.append("};")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, "w").write("\n".join(out) + "\n")
    print("wrote %s" % dst)


if __name__ == "__main__":
    main()
